# Configurações de porta e o caminho do repositório GIT 
# dos arquivos de configuração das APIs

server:
  port: 9090

spring:
  cloud:
    config:
      server:
        git:
          uri: C:\Leo\Desenvolvimento\Microservices\config-repo